# Generated by Django 5.2.15 on 2026-06-15 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_level', models.CharField(choices=[('low', 'Тёмное помещение'), ('medium', 'Среднее освещение'), ('bright', 'Яркое освещение')], max_length=10, verbose_name='Освещённость')),
                ('humidity', models.CharField(choices=[('low', 'Сухой воздух'), ('medium', 'Нормальная влажность'), ('high', 'Влажный воздух')], max_length=10, verbose_name='Влажность')),
                ('temperature', models.IntegerField(verbose_name='Температура, °C')),
                ('room_size', models.CharField(choices=[('small', 'Маленькое'), ('medium', 'Среднее'), ('large', 'Большое')], max_length=10, verbose_name='Размер помещения')),
                ('has_pets', models.BooleanField(default=False, verbose_name='Есть домашние животные')),
                ('care_time', models.CharField(choices=[('minimal', 'Минимум времени'), ('average', 'Умеренно'), ('much', 'Много времени')], max_length=10, verbose_name='Свободное время на уход')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подбора')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_conditions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметры помещения',
                'verbose_name_plural': 'Параметры помещений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(verbose_name='Совместимость, %')),
                ('reasons', models.TextField(blank=True, verbose_name='Пояснения')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='catalog.plant', verbose_name='Растение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='selector.roomcondition', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Результат подбора',
                'verbose_name_plural': 'Результаты подбора',
                'ordering': ['-match_score'],
            },
        ),
    ]
