# Generated by Django 5.2.15 on 2026-06-15 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория растений',
                'verbose_name_plural': 'Категории растений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('scientific_name', models.CharField(blank=True, max_length=150, verbose_name='Научное название')),
                ('light_needs', models.CharField(choices=[('low', 'Тень / слабый свет'), ('medium', 'Рассеянный свет'), ('bright', 'Яркий свет')], max_length=10, verbose_name='Потребность в свете')),
                ('humidity_needs', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=10, verbose_name='Потребность во влажности')),
                ('temp_min', models.IntegerField(verbose_name='Минимальная температура, °C')),
                ('temp_max', models.IntegerField(verbose_name='Максимальная температура, °C')),
                ('toxicity', models.BooleanField(default=False, verbose_name='Токсично для животных')),
                ('care_difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Сложность ухода')),
                ('water_frequency', models.CharField(choices=[('rare', 'Редкий'), ('regular', 'Регулярный'), ('frequent', 'Частый')], max_length=10, verbose_name='Частота полива')),
                ('max_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная высота, см')),
                ('image', models.ImageField(blank=True, upload_to='plants/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='catalog.plantcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('temp_min__lte', models.F('temp_max'))), name='catalog_plant_temp_range_valid')],
            },
        ),
    ]
